name: Build Packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
        tag:
          - openwrt-24.10
          - openwrt-25.12

    steps:
      - name: Checkout helloworld
        uses: actions/checkout@v6
        with:
          repository: sbwml/openwrt_helloworld
          path: helloworld
          fetch-depth: 0

      - name: Checkout mosdns
        uses: actions/checkout@v6
        with:
          repository: sbwml/luci-app-mosdns
          path: mosdns

      - name: Checkout node
        uses: actions/checkout@v6
        with:
          repository: sbwml/feeds_packages_lang_node-prebuilt
          path: node

      - name: Diff tree
        run: |
          ls
          sudo timedatectl set-timezone 'Asia/Shanghai'
          diff_tree="$(git -C helloworld log --since="yesterday" --until="now" --pretty=format:"%H" | xargs -I{} git -C helloworld diff-tree --no-commit-id --name-only -r {} | cut -d/ -f1 | sort -u | tr '\n' ' ' | sed 's/ $//') v2ray-geodata vmlinux-btf"
          echo "NEED_BUILD=$diff_tree" >> $GITHUB_ENV
          git -C helloworld log --since="yesterday" --until="now" --pretty=format:"%H" | xargs -I{} git -C helloworld diff-tree --no-commit-id --name-only -r {} | cut -d/ -f1 | sort -u | tr '\n' ' ' | sed 's/ $//'
          echo $diff_tree
