name: Build Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        tag:
          - openwrt-24.10
          - openwrt-25.12

    steps:
      - name: Clone
        run: |
          git clone https://github.com/sbwml/openwrt_helloworld helloworld
          git clone https://github.com/sbwml/luci-app-mosdns mosdns
          git clone https://github.com/sbwml/feeds_packages_lang_node-prebuilt node

      - name: Compute ARCH / effective arch
        run: |
          echo "SKIP_BUILD=0" >> $GITHUB_ENV
          if [ "${{ matrix.tag }}" = "openwrt-25.12" ] && [ "${{ matrix.arch }}" = "riscv64_riscv64" ]; then
            echo "EFFECTIVE_ARCH=riscv64_generic" >> $GITHUB_ENV
            echo "ARCH=riscv64_generic-${{ matrix.tag }}" >> $GITHUB_ENV
          elif [ "${{ matrix.tag }}" = "openwrt-25.12" ] && [ "${{ matrix.arch }}" = "mips_4kec" ]; then
            echo "SKIP_BUILD=1" >> $GITHUB_ENV
          else
            echo "EFFECTIVE_ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
            echo "ARCH=${{ matrix.arch }}-${{ matrix.tag }}" >> $GITHUB_ENV
          fi

      - name: Build Packages
        if: ${{ env.SKIP_BUILD == '0' }}
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          FEEDNAME: packages_ci
          PACKAGES: dns2socks
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true
          V: s

      - name: Create compress files
        if: ${{ env.SKIP_BUILD == '0' }}
        continue-on-error: true
        run: |
          tar -zcvf ${{ env.ARCH }}.tar.gz -C bin/packages/${{ env.EFFECTIVE_ARCH }}/ packages_ci
          echo "latest_release=$(TZ='Asia/Shanghai' date +%Y-%m-%d)" >>$GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.model }}-${{ matrix.tag.version }}
          path: ${{ env.ARCH }}.tar.gz

      - name: Upload FTP (lftp)
        if: ${{ env.SKIP_BUILD == '0' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -e "
            set ftp:ssl-allow no;
            mirror --reverse \
                   --only-newer \
                   --verbose \
                   --no-perms \
                   --exclude-glob .git* \
                   bin/packages/${{ env.EFFECTIVE_ARCH }}/packages_ci/ \
                   ${{ matrix.tag }}/${{ env.EFFECTIVE_ARCH }}/;
            bye
          " -u "${{ secrets.ftp_username }},${{ secrets.ftp_password }}" ${{ secrets.ftp_address }}


      - name: Create metadata (ipk)
        if: ${{ env.SKIP_BUILD == '0' && matrix.tag == 'openwrt-24.10' }}
        run: |
          sshpass -p ${{ secrets.server_password }} ssh -o StrictHostKeyChecking=no root@${{ secrets.ftp_address }} >/dev/null 2>&1
          sshpass -p ${{ secrets.server_password }} ssh root@${{ secrets.ftp_address }} "/opt/sbin/opkg-sign ${{ matrix.tag }} ${{ env.EFFECTIVE_ARCH }}"

      - name: Create metadata (apk)
        if: ${{ env.SKIP_BUILD == '0' && matrix.tag == 'openwrt-25.12' }}
        run: |
          sshpass -p ${{ secrets.server_password }} ssh -o StrictHostKeyChecking=no root@${{ secrets.ftp_address }} >/dev/null 2>&1
          sshpass -p ${{ secrets.server_password }} ssh root@${{ secrets.ftp_address }} "/opt/sbin/apk-sign ${{ matrix.tag }} ${{ env.EFFECTIVE_ARCH }}"
